# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import dfs_pb2 as dfs__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in dfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class DFSStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreChunk = channel.unary_unary(
                '/DFS/StoreChunk',
                request_serializer=dfs__pb2.StoreChunkRequest.SerializeToString,
                response_deserializer=dfs__pb2.StoreChunkResponse.FromString,
                _registered_method=True)
        self.RetrieveChunk = channel.unary_unary(
                '/DFS/RetrieveChunk',
                request_serializer=dfs__pb2.RetrieveChunkRequest.SerializeToString,
                response_deserializer=dfs__pb2.RetrieveChunkResponse.FromString,
                _registered_method=True)


class DFSServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StoreChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DFSServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreChunk,
                    request_deserializer=dfs__pb2.StoreChunkRequest.FromString,
                    response_serializer=dfs__pb2.StoreChunkResponse.SerializeToString,
            ),
            'RetrieveChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveChunk,
                    request_deserializer=dfs__pb2.RetrieveChunkRequest.FromString,
                    response_serializer=dfs__pb2.RetrieveChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'DFS', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('DFS', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DFS(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StoreChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DFS/StoreChunk',
            dfs__pb2.StoreChunkRequest.SerializeToString,
            dfs__pb2.StoreChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/DFS/RetrieveChunk',
            dfs__pb2.RetrieveChunkRequest.SerializeToString,
            dfs__pb2.RetrieveChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
