# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dfs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdfs.proto\"O\n\x11StoreChunkRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\x12\x12\n\nchunk_data\x18\x03 \x01(\x0c\"$\n\x12StoreChunkResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\">\n\x14RetrieveChunkRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63hunk_index\x18\x02 \x01(\x05\"+\n\x15RetrieveChunkResponse\x12\x12\n\nchunk_data\x18\x01 \x01(\x0c\x32|\n\x03\x44\x46S\x12\x35\n\nStoreChunk\x12\x12.StoreChunkRequest\x1a\x13.StoreChunkResponse\x12>\n\rRetrieveChunk\x12\x15.RetrieveChunkRequest\x1a\x16.RetrieveChunkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dfs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STORECHUNKREQUEST']._serialized_start=13
  _globals['_STORECHUNKREQUEST']._serialized_end=92
  _globals['_STORECHUNKRESPONSE']._serialized_start=94
  _globals['_STORECHUNKRESPONSE']._serialized_end=130
  _globals['_RETRIEVECHUNKREQUEST']._serialized_start=132
  _globals['_RETRIEVECHUNKREQUEST']._serialized_end=194
  _globals['_RETRIEVECHUNKRESPONSE']._serialized_start=196
  _globals['_RETRIEVECHUNKRESPONSE']._serialized_end=239
  _globals['_DFS']._serialized_start=241
  _globals['_DFS']._serialized_end=365
# @@protoc_insertion_point(module_scope)
